local ADDON, ns = ...

ns.QuartierMiniature = ns.QuartierMiniature or {}

local QM = ns.QuartierMiniature

QM.Config = QM.Config or {}
QM.Config.mapId = QM.Config.mapId or "village_01"
QM.Config.mapWidth = QM.Config.mapWidth or 2048
QM.Config.mapHeight = QM.Config.mapHeight or 1024
QM.Config.backgroundPath = QM.Config.backgroundPath
	or "Interface\\AddOns\\WoWGuilde\\Media\\MiniGames\\QuartierMiniature\\LittleVillage_Background_01.tga"

QM.Config.maps = QM.Config.maps
	or {
		village_01 = {
			mapWidth = QM.Config.mapWidth,
			mapHeight = QM.Config.mapHeight,
			backgroundPath = QM.Config.backgroundPath,
		},
	}

QM.Config.nineSlice = QM.Config.nineSlice or {
	enabled = true,
	inset = 0,
	alpha = 1,
	frameLevelOffset = 8,
}

QM.Config.zoom = QM.Config.zoom or {
	minFactor = 1.0,
	maxFactor = 2.0,
	wheelFactor = 1.08,
}

QM.Config.time = QM.Config.time
	or {
		dayDurationSec = 7200,
		timelinePreset = "narrative_balanced",
		blendTailRatio = 0.20,
		defaultTimeScale = 1.0,
		hudEnabled = true,
	}

QM.Config.objects = QM.Config.objects
	or {
		updateInterval = 0,
		worldOffsetScale = 0.01,
		verticalScale = 0.20,
		zToXCompensation = 0.0,
		zToYCompensation = 0.0,
		colorTemperature = 0.0,
		lightColorR = 1.0,
		lightColorG = 1.0,
		lightColorB = 1.0,
		lightLuminance = 1.0,
		rotationMode = "screen", -- "screen" (intuitif) or "legacy"
		baseRotX = 90, -- vue du dessus par defaut (axe camera en haut)
		baseRotY = 0, -- rotation de base (visuelle) pour Rot Y
		baseRotZ = 0, -- rotation de base (visuelle) pour Rot Z
		lockToMap = false,
		zoomModelScale = true,
		zoomScaleFactor = 1.0,
		zoomScaleExponent = 1.0,
		debugLogs = true,
		debugObjectId = "obj_8", -- "*" to log every object
	}

QM.Config.npc = QM.Config.npc
	or {
		count = 10,
		boundPad = 0.04,
		speedMin = 0.008,
		speedMax = 0.014,
		baseSize = 46,
		iconSize = 30,
		showNames = true,
		nameFontSize = 11,
		nameMaxLen = 22,
		persistSaveInterval = 4.0,
		updateStep = 0.040,
		maxCatchupSteps = 2,
		lowCpuMode = true,
		lowCpuNpcStride = 1,
		lowCpuMoveMaxLoops = 12,
		lowCpuProbeCount = 6,
		lowCpuRescueCount = 6,
		enableCollisions = false,
		intentQueueMax = 12,
		autoIntentEnabled = true,
		autoIntentIntervalMin = 5.0,
		autoIntentIntervalMax = 12.0,
		autoIntentMaxQueue = 1,
		autoSocialConversations = true,
		spatialGridCell = 0.060,
		idleFastPath = true,
		inspector = {
			enabled = true,
			anchor = "BOTTOMRIGHT",
			offsetX = -16,
			offsetY = 16,
			selectRadiusPx = 26,
			clickMaxTravelPx = 6,
			clickMaxDuration = 0.25,
			refreshInterval = 0.20,
		},
		ringWidth = 40,
		ringHeight = 40,
		ringOffsetX = 0,
		ringOffsetY = 0,
		ringAvoidanceOffsetPx = 6,
		enforceRingSeparation = false,
		shadowWidth = 70,
		shadowHeight = 80,
		shadowOffsetY = -8,
		routeToRouteSwitchDist = 0.28,
		routeToPlazaSwitchDist = 0.30,
		plazaToRouteSwitchDist = 0.30,
		maxPerZone = 3,
		maxActionsPerZone = 3,
		proximitySwitchCooldown = 1.0,
		transitionSpeedFactor = 1.35,
		routeWalkHalfWidth = 0.020,
		routeOppositePassFactor = 0.58,
		routeOppositeMinDelta = 2.20,
		manualPathRealtimeReplan = false,
		manualPathReplanInterval = 1.20,
		manualPathSmoothStep = 0.022,
		manualPathMaxPoints = 20,
		zoneShiftPathMaxPoints = 12,
		manualPathPlazaFactor = 1.35,
		manualPathPlazaEdgeMaxDist = 0.065,
		manualPathJunctionDist = 0.028,
		manualPathJunctionPenalty = 1.08,
		crowdExpandSenseRadius = 0.060,
		crowdExpandThreshold = 3,
		crowdExpandMaxBonus = 0.016,
		crowdRelocateMaxRadius = 0.045,
		crowdRelocateMinDistFactor = 0.58,
		walkStep = 0.010,
		walkTurnRate = 2.8,
		walkDesiredJitter = 0.65,
		walkLookAhead = 0.020,
		walkSpeedBlend = 2.2,
		longGoalMinDist = 0.16,
		longGoalMaxDist = 0.46,
		longGoalRetargetMin = 4.0,
		longGoalRetargetMax = 10.0,
		longGoalReach = 0.020,
		longGoalPlazaBias = 0.62,
		poiPickChance = 0.60,
		poiPickRadius = 0.090,
		poiObserveMinApproach = 0.018,
		poiContemplateMin = 20.0,
		poiContemplateMax = 40.0,
		poiScanMaxPerRoll = 24,
		poiNearRadius = 0.030,
		poiPauseMultMin = 1.8,
		poiPauseMultMax = 3.0,
		poiCooldownMin = 24.0,
		poiCooldownMax = 40.0,
		plazaRoamRetargetMin = 1.6,
		plazaRoamRetargetMax = 3.8,
		personalSpace = 0.018,
		crowdSenseRadius = 0.075,
		crowdMinSpeedFactor = 0.35,
		waitMin = 0.80,
		waitMax = 2.60,
		waitNearChance = 0.22,
		reverseChance = 0.01,
		encounterChance = 0.22,
		encounterCheckMin = 0.20,
		encounterCheckMax = 0.65,
		encounterSameDirectionBlockDelta = 0.95,
		encounterNearMax = 4,
		encounterRadius = 0.060,
		encounterMinDist = 0.015,
		approachStopDist = 0.032,
		discussMin = 8.0,
		discussMax = 16.0,
		autoSmallTalkMin = 4.0,
		autoSmallTalkMax = 9.0,
		discussPreferredDist = 0.031,
		discussMinDist = 0.026,
		discussVariance = 0.30,
		discussLongChance = 0.22,
		discussLongMultMin = 1.20,
		discussLongMultMax = 2.00,
		socialCooldownMin = 1.2,
		socialCooldownMax = 3.0,
		globalTalkLockDuration = 20.0,
		postTalkCooldownMin = 6.0,
		postTalkCooldownMax = 16.0,
		repeatPartnerCooldownMin = 10.0,
		repeatPartnerCooldownMax = 24.0,
		postTalkZoneSwitchMin = 3.5,
		postTalkZoneSwitchMax = 8.0,
		postTalkZoneReach = 0.016,
		disengageMinDist = 0.042,
		disengageMin = 0.9,
		disengageMax = 2.4,
		duoWalkChance = 0.02,
		duoWalkMin = 3.5,
		duoWalkMax = 9.0,
		duoWalkSeparation = 0.030,
		duoTargetRadius = 0.080,
		duoTargetReach = 0.020,
		autoSocialConversations = true,
		autoSocialMaxReserve = 70,
		autoSocialTriggerChanceMin = 0.04,
		autoSocialTriggerChanceMax = 0.22,
		socialPlayerTalkGainMin = 20,
		socialPlayerTalkGainMax = 25,
		socialAutoTalkGainMin = 10,
		socialAutoTalkGainMax = 15,
		socialPairSoftMinDist = 0.015,
		discussSoftMinDist = 0.026,
		selfPauseChance = 0.08,
		selfPauseMin = 1.2,
		selfPauseMax = 3.8,
		selfPauseCooldownMin = 3.0,
		selfPauseCooldownMax = 8.0,
		selfPauseEdgeMinDist = 0.004,
		selfPauseEdgeMaxDist = 0.022,
		selfPauseZoneCell = 0.025,
		minSeparationPx = 20,
		spawnMinDist = 0.028,
		emergencySeparationMult = 1.25,
		separationInterval = 0.08,
		defaultNames = {
			"Aline",
			"Bran",
			"Cedric",
			"Dalia",
			"Elora",
			"Faris",
			"Galen",
			"Hana",
			"Isen",
			"Jora",
			"Kael",
			"Liora",
		},
		needs = {
			enabled = true,
			initialMin = 78,
			initialMax = 96,
			socialRisePerSec = 0.045,
			socialRecoverTalkPerSec = 0.180,
			socialRecoverLieuGroupPerSec = 0.030,
			socialLieuGroupMinCount = 2,
			fatigueRiseMovePerSec = 0.085,
			fatigueRecoverRestPerSec = 0.095,
			faimRisePerSec = 0.055,
			faimRecoverPausePerSec = 0.090,
			distractionRisePerSec = 0.045,
			distractionRecoverPausePerSec = 0.090,
			essentialHoldMin = 60,
			essentialHoldMax = 80,
			essentialRecoverBoost = 12.0,
			essentialHoldMarginSec = 0.75,
			fatigueSpeedPenalty = 0.45,
			socialUrgencyThreshold = 66,
			distractionPauseThreshold = 72,
		},
		zoneRoutineActionsPerZone = 3,
		zoneRoutinePauseMin = 3.2,
		zoneRoutinePauseMax = 7.8,
		zoneRoutineTargetTtlMin = 8.0,
		zoneRoutineTargetTtlMax = 16.0,
	}
